/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.IndividualView;

import View.MainView;

/**
 *
 * @author HP
 */
public class ViewStudentMedicalRequirement extends javax.swing.JPanel {
    
    MainView mv;

    /**
     * Creates new form AddStudentSchoolInfo
     */
    public ViewStudentMedicalRequirement() {
        initComponents();
    }
    
    public ViewStudentMedicalRequirement(MainView mf) {
        initComponents();
        this.mv = mf;
    }
    
    public void set_student_name(String student_name){
        this.studentNameValueLabel.setText(student_name);
    }
    
    public void set_medical_requirement(String medical_requirement){
        this.medicalRequirementValueLabel.setText(medical_requirement);
    }
    
    public void set_first_date_of_diagnose(String first_date_of_diagnose){
        this.firstDateOfDiagnoseValueLabel.setText(first_date_of_diagnose);
    }
    
    public void set_first_date_of_getting_treatment(String first_date_of_treatment){
        this.firstDateOfTreatmentValueLabel.setText(first_date_of_treatment);
    }
    
    public void set_last_date_of_treatment(String last_date_of_treatment){
        this.lastDateOfTreatmentValueLabel.setText(last_date_of_treatment);
    }
    
    public void set_details(String details){
        this.detailsTextField.setText(details);
        this.detailsTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topicLabel = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        firstDateOfTreatmentLabel = new javax.swing.JLabel();
        detailsLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        medicalRequirementLabel = new javax.swing.JLabel();
        firstDateOfDiagnoseLabel = new javax.swing.JLabel();
        lastDateOfTraetementLabel = new javax.swing.JLabel();
        detailsTextField = new javax.swing.JTextField();
        studentNameValueLabel = new javax.swing.JLabel();
        medicalRequirementValueLabel = new javax.swing.JLabel();
        firstDateOfDiagnoseValueLabel = new javax.swing.JLabel();
        firstDateOfTreatmentValueLabel = new javax.swing.JLabel();
        lastDateOfTreatmentValueLabel = new javax.swing.JLabel();

        topicLabel.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        topicLabel.setText("ශිෂ්‍ය විශේෂ සෞඛ්‍ය අවශ්‍යතා පිලිබද විස්තර");

        studentNameLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        studentNameLabel.setText("සිසු/සිසුවියගේ නම:");

        firstDateOfTreatmentLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        firstDateOfTreatmentLabel.setText("පලමුවෙන් ප්‍රතිකාර ලද දිනය:");

        detailsLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        detailsLabel.setText("විස්තර:");

        closeButton.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        closeButton.setText("වසා දමන්න");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        medicalRequirementLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        medicalRequirementLabel.setText("විශේෂ සෞඛ්‍ය තත්වය:");

        firstDateOfDiagnoseLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        firstDateOfDiagnoseLabel.setText("හදුනාගත් පලමු දිනය:");

        lastDateOfTraetementLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        lastDateOfTraetementLabel.setText("ප්‍රතිකාර ලද අවසන් දිනය:");

        detailsTextField.setFont(new java.awt.Font("Iskoola Pota", 0, 12)); // NOI18N
        detailsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsTextFieldActionPerformed(evt);
            }
        });

        studentNameValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        studentNameValueLabel.setText("student name value");

        medicalRequirementValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        medicalRequirementValueLabel.setText("medical requirement value");

        firstDateOfDiagnoseValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        firstDateOfDiagnoseValueLabel.setText("first date of diagnose");

        firstDateOfTreatmentValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        firstDateOfTreatmentValueLabel.setText("first date of treatment");

        lastDateOfTreatmentValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        lastDateOfTreatmentValueLabel.setText("last date of treatment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(medicalRequirementLabel)
                                    .addComponent(studentNameLabel))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medicalRequirementValueLabel)
                                    .addComponent(studentNameValueLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstDateOfTreatmentLabel)
                                    .addComponent(lastDateOfTraetementLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstDateOfDiagnoseLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(detailsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastDateOfTreatmentValueLabel)
                                    .addComponent(detailsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstDateOfTreatmentValueLabel)
                                    .addComponent(firstDateOfDiagnoseValueLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(closeButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(topicLabel)))
                .addContainerGap(743, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(topicLabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(studentNameValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalRequirementLabel)
                    .addComponent(medicalRequirementValueLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstDateOfDiagnoseLabel)
                    .addComponent(firstDateOfDiagnoseValueLabel))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstDateOfTreatmentLabel)
                    .addComponent(firstDateOfTreatmentValueLabel))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastDateOfTraetementLabel)
                    .addComponent(lastDateOfTreatmentValueLabel))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(detailsLabel)))
                .addGap(56, 56, 56)
                .addComponent(closeButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsTextFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.mv.close_tab();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddStudentMedicalRequirement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddStudentMedicalRequirement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddStudentMedicalRequirement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddStudentMedicalRequirement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddStudentMedicalRequirement().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JTextField detailsTextField;
    private javax.swing.JLabel firstDateOfDiagnoseLabel;
    private javax.swing.JLabel firstDateOfDiagnoseValueLabel;
    private javax.swing.JLabel firstDateOfTreatmentLabel;
    private javax.swing.JLabel firstDateOfTreatmentValueLabel;
    private javax.swing.JLabel lastDateOfTraetementLabel;
    private javax.swing.JLabel lastDateOfTreatmentValueLabel;
    private javax.swing.JLabel medicalRequirementLabel;
    private javax.swing.JLabel medicalRequirementValueLabel;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel studentNameValueLabel;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
