/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.IndividualView;

import View.MainView;

/**
 *
 * @author HP
 */
public class ViewStudentFamilyInfo extends javax.swing.JPanel {
    
    MainView mv;

    /**
     * Creates new form AddStudentFamilyInfo
     */
    public ViewStudentFamilyInfo() {
        initComponents();
    }
    
    public ViewStudentFamilyInfo(MainView mf) {
        initComponents();
        this.mv = mf;
    }
    
    public void set_student_name(String student_name){
        this.studentNameValueLabel.setText(student_name);
    }
    
    public void set_family_member_name(String family_member_name){
        this.familyMemberNameValueLabel.setText(family_member_name);
    }
    
    public void set_relationship(String relationship){
        this.relationshipValueLabel.setText(relationship);
    }
    
    public void set_fm_birthday(String fm_birthday){
        this.birthdayValueLabel.setText(fm_birthday);
    }
    
    public void set_nic(String nic){
        this.nicValueLabel.setText(nic);
    }
    
    public void set_career(String career){
        this.careerValueLabel.setText(career);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topicLabel = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        fmemberNameLabel = new javax.swing.JLabel();
        relationshipLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        careerLabel = new javax.swing.JLabel();
        studentNameValueLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        familyMemberNameValueLabel = new javax.swing.JLabel();
        relationshipValueLabel = new javax.swing.JLabel();
        birthdayValueLabel = new javax.swing.JLabel();
        nicValueLabel = new javax.swing.JLabel();
        careerValueLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(595, 731));

        topicLabel.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        topicLabel.setText("ශිෂ්‍යයන්ගේ පවුලේ තොරතුරු");

        studentNameLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        studentNameLabel.setText("සිසු/සිසුවියගේ නම:");

        fmemberNameLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        fmemberNameLabel.setText("පවුලේ සාමාජිකයාගේ නම:");

        relationshipLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        relationshipLabel.setText("නෑකම:");

        birthdayLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        birthdayLabel.setText("උපන් දිනය:");

        nicLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        nicLabel.setText("ජාතික හැදුනුම්පත් අංකය:");

        careerLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        careerLabel.setText("ජීවනෝපාය:");

        studentNameValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        studentNameValueLabel.setText("studentNameValueLabel");

        closeButton.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        closeButton.setText("වසා දමන්න");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        familyMemberNameValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        familyMemberNameValueLabel.setText("family member name");

        relationshipValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        relationshipValueLabel.setText("relationship");

        birthdayValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        birthdayValueLabel.setText("birthday");

        nicValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        nicValueLabel.setText("nic");

        careerValueLabel.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        careerValueLabel.setText("career");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(nicLabel))
                                    .addComponent(careerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(birthdayLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(relationshipLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fmemberNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(studentNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(familyMemberNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(relationshipValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birthdayValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nicValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(careerValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(closeButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(topicLabel)))
                .addContainerGap(753, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(topicLabel)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(studentNameValueLabel))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmemberNameLabel)
                    .addComponent(familyMemberNameValueLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationshipLabel)
                    .addComponent(relationshipValueLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayLabel)
                    .addComponent(birthdayValueLabel))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel)
                    .addComponent(nicValueLabel))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(careerLabel)
                    .addComponent(careerValueLabel))
                .addGap(66, 66, 66)
                .addComponent(closeButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.mv.close_tab();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddStudentFamilyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddStudentFamilyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddStudentFamilyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddStudentFamilyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddStudentFamilyInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JLabel birthdayValueLabel;
    private javax.swing.JLabel careerLabel;
    private javax.swing.JLabel careerValueLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel familyMemberNameValueLabel;
    private javax.swing.JLabel fmemberNameLabel;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel nicValueLabel;
    private javax.swing.JLabel relationshipLabel;
    private javax.swing.JLabel relationshipValueLabel;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel studentNameValueLabel;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
