/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.List;

import Controller.GradeController;
import Controller.StudentController;
import View.Add.AddGradeExam;
import View.MainView;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import View.IndividualView.Student.ViewStudent_fromList;
import View.Add.AddStudentFamilyInfo;
import Controller.StudentFamilyMemberController;
import View.Add.AddStudentSchoolInfo;

/**
 *
 * @author HP
 */
public class StudentList extends javax.swing.JPanel {
    
    MainView mv;

    /**
     * Creates new form StudentList
     */
    public StudentList() {
        initComponents();
    }
    
    public StudentList(MainView mf) {
        initComponents();
        this.mv = mf;
        this.loadGrades();
        this.load_table("","","",0,"");
    }
    
   public void loadGrades(){
        GradeController gc = new GradeController();
        try {
            gradeComboBx.addItem("Select grade");
            HashMap<Integer, Map<Integer,String>> hm = gc.getAllGrades();
            if(!hm.isEmpty()){
                hm.forEach((key,value) -> {
                    gradeComboBx.addItem(value.get(1));
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void load_table(String student_name, String student_code, String medical_status,int grade, String school){
        StudentController sc = new StudentController();
        HashMap<Integer, Map<Integer,String>> mp = sc.ListStudents(student_name, student_code, medical_status, grade, school);
        System.out.println("The student list is: " + mp);
        this.clearTable(studentInformationTable);
        this.createTable(mp, studentInformationTable);
    }
    
    public void clearTable(JTable tbl){
    
        DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
        int row_count = dtm.getRowCount();
        
        for(int i = row_count-1;i>=0;i--){
            dtm.removeRow(i);
        }
    
    }
    
    public void createTable(HashMap hm, JTable tbl){
        if(!hm.isEmpty()){
            hm.forEach((key,value) -> {
                HashMap<Integer,String> hsh = (HashMap) value;
                //System.out.println("hashmap: "+hsh);
                int hlength = hsh.size();
                String[] tbl_data=new String[hlength];
                hsh.forEach((k,v) -> {
                    tbl_data[k] = v;
                    //System.out.println("The grade value: " + v);
                });
                DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
                dtm.addRow(tbl_data);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topicLabel = new javax.swing.JLabel();
        studentCodeText = new javax.swing.JTextField();
        medicalStatusText = new javax.swing.JTextField();
        schoolText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        studentNameLabel = new javax.swing.JLabel();
        studentCodeLabel = new javax.swing.JLabel();
        schoolLabel = new javax.swing.JLabel();
        medicalStatusLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        studentNameText = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        oldStudentButton = new javax.swing.JButton();
        addFamilyMemberButton = new javax.swing.JButton();
        addSchoolButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentInformationTable = new javax.swing.JTable();
        gradeComboBx = new javax.swing.JComboBox<>();

        topicLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topicLabel.setText("All Student's Information");

        studentCodeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        medicalStatusText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        schoolText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        studentNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentNameLabel.setText("Student name:");

        studentCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentCodeLabel.setText("Student code:");

        schoolLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        schoolLabel.setText("School:");

        medicalStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        medicalStatusLabel.setText("Medical status:");

        gradeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gradeLabel.setText("Grade:");

        studentNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editButton.setText("Edit");

        oldStudentButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oldStudentButton.setText("Old student");

        addFamilyMemberButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addFamilyMemberButton.setText("Add family member");
        addFamilyMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFamilyMemberButtonActionPerformed(evt);
            }
        });

        addSchoolButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addSchoolButton.setText("Add School");
        addSchoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchoolButtonActionPerformed(evt);
            }
        });

        viewButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        studentInformationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date of Birth", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentInformationTable);

        gradeComboBx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oldStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addFamilyMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addSchoolButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentNameLabel)
                                    .addComponent(studentCodeLabel)
                                    .addComponent(medicalStatusLabel)
                                    .addComponent(gradeLabel)
                                    .addComponent(schoolLabel))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(schoolText)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                    .addComponent(studentCodeText)
                                    .addComponent(medicalStatusText)
                                    .addComponent(studentNameText)
                                    .addComponent(gradeComboBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(topicLabel)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(topicLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(studentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentCodeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medicalStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gradeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(schoolLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medicalStatusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradeComboBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(schoolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(clearButton))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(oldStudentButton)
                    .addComponent(addFamilyMemberButton)
                    .addComponent(addSchoolButton)
                    .addComponent(viewButton))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String student_name = studentNameText.getText();
        String student_code = studentCodeText.getText();
        String medical_status = medicalStatusText.getText();
        int grade_id = 0;
        if(!gradeComboBx.getSelectedItem().equals("Select grade")){
            String grade = gradeComboBx.getSelectedItem().toString();
            GradeController gc = new GradeController();
            try {
                grade_id = gc.getGradeId(grade);
            } catch (SQLException ex) {
                Logger.getLogger(AddGradeExam.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String school = schoolText.getText();
        this.load_table(student_name, student_code, medical_status, grade_id, school);
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        this.clearSearchContent();
        this.load_table("", "", "", 0, "");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int row = studentInformationTable.getSelectedRow();
        if(row > -1){
            DefaultTableModel dtm = (DefaultTableModel) studentInformationTable.getModel();
            int id = Integer.parseInt(dtm.getValueAt(row, 0).toString());
            int grade = Integer.parseInt(dtm.getValueAt(row, 3).toString());
            GradeController gc = new GradeController();
            String grade_in_text = gc.get_grade_in_words(grade);
            StudentController sc = new StudentController();
            List<String> l = sc.get_student_details_by_id(id);
            ViewStudent_fromList vsfl = new ViewStudent_fromList(mv, id);
            vsfl.setName(l.get(0));
            vsfl.setAddress(l.get(1));
            vsfl.setBirthday(l.get(2));
            vsfl.setContactNumber(l.get(3));
            vsfl.setPhoto(l.get(4));
            vsfl.setIdentityCode(l.get(5));
            vsfl.setPassportLabel(l.get(6));
            vsfl.setDateOfEntarance(l.get(7));
            vsfl.setGradeInYearOfEntarance(l.get(8));
            vsfl.setCurrentGrade(grade_in_text);
            mv.add_new_component(vsfl, "Student Information");
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void addFamilyMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFamilyMemberButtonActionPerformed
        // TODO add your handling code here:
        int row = studentInformationTable.getSelectedRow();
        if(row > -1){
            DefaultTableModel dtm = (DefaultTableModel) studentInformationTable.getModel();
            int id = Integer.parseInt(dtm.getValueAt(row, 0).toString());
            String name = dtm.getValueAt(row, 1).toString();
            AddStudentFamilyInfo adsfi = new AddStudentFamilyInfo(mv, id);
            adsfi.set_student_name(name);
            mv.add_new_component(adsfi, "Add Student Family Information");
        }
        
    }//GEN-LAST:event_addFamilyMemberButtonActionPerformed

    private void addSchoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchoolButtonActionPerformed
        // TODO add your handling code here:
        int row = studentInformationTable.getSelectedRow();
        if(row > -1){
            DefaultTableModel dtm = (DefaultTableModel) studentInformationTable.getModel();
            int id = Integer.parseInt(dtm.getValueAt(row, 0).toString());
            String name = dtm.getValueAt(row, 1).toString();
            AddStudentSchoolInfo adssi = new AddStudentSchoolInfo(mv, id);
            adssi.set_student_name(name);
            mv.add_new_component(adssi, "Add Student School Information");
        }
    }//GEN-LAST:event_addSchoolButtonActionPerformed
    
    private void clearSearchContent(){
        studentNameText.setText("");
        studentCodeText.setText("");
        medicalStatusText.setText("");
        gradeComboBx.setSelectedIndex(0);
        schoolText.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFamilyMemberButton;
    private javax.swing.JButton addSchoolButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton editButton;
    private javax.swing.JComboBox<String> gradeComboBx;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel medicalStatusLabel;
    private javax.swing.JTextField medicalStatusText;
    private javax.swing.JButton oldStudentButton;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JTextField schoolText;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel studentCodeLabel;
    private javax.swing.JTextField studentCodeText;
    private javax.swing.JTable studentInformationTable;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JTextField studentNameText;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
