/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Edit;

import Controller.UserController;
import View.MessageBox.FormValidation;
import View.MessageBox.Result_ErrorMessage;
import View.MessageBox.Result_SuccessMessage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;
import View.MainView;
import javax.swing.JList;

/**
 *
 * @author HP
 */
public class EditUser extends javax.swing.JPanel {
    
    MainView mv;
    int user_id = 0;

    /**
     * Creates new form EditUser
     */
    public EditUser() {
        initComponents();
    }
    
    public EditUser(MainView mf) {
        initComponents();
        this.mv = mf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        okButton.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        okButton.setText("යොමු කරන්න");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        cancelButton.setText("අවලංගු කරන්න");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nameText.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        userNameText.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        passwordText.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel2.setText("සම්පූර්ණ නම:");

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel3.setText("පද්ධතිය සදහා භාවිත කරන නම:");

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel4.setText("භාවිතයට නියමිත පුද්ගලික කේතය:");

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel1.setText("පද්ධතිය පරිහරණය කරන්නන් යාවත්කාලීන කිරීම");

        clearButton.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        clearButton.setText("මකා දමන්න");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        userList.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userList);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("*");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setText("*");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(okButton)
                        .addGap(114, 114, 114)
                        .addComponent(cancelButton)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(passwordText)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(clearButton)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearButton)
                            .addComponent(jLabel20)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        String name = this.nameText.getText();
        String user_name = this.userNameText.getText();
        String password = this.passwordText.getText();

        if(!name.equals("") && !user_name.equals("") && !password.equals("") && user_id > 0){
            List<String> l = new ArrayList<String>();
            l.add(0, Integer.toString(user_id));
            l.add(1, name);
            l.add(2, user_name);
            l.add(3, password);

            UserController uc = new UserController();
            int i = uc.update_user(l);
            if(i > 0){
                Result_SuccessMessage rsm = new Result_SuccessMessage();
                rsm.setMessage("මෙම තොරතුරු පද්ධතියේ නවමු භාවිත කරන්නා පිලිබද තොරතුරු සාර්ථක ලෙස මෙම දත්ත පද්ධතිය තුල යාවත්කාලීන විය");
                rsm.setVisible(true);

                this.nameText.setText("");
                this.userNameText.setText("");
                this.passwordText.setText("");
                user_id = 0;
            }else if(i < 0){
                Result_ErrorMessage rem = new Result_ErrorMessage();
                rem.setMessage("කරුණාකර වෙනත් භාවිත නාමයක් සහ පුද්ගලික කේතයක් භාවිතා කරන්න");
                rem.setVisible(true);
            }else{
                Result_ErrorMessage rem = new Result_ErrorMessage();
                rem.setMessage("මෙම තොරතුරු පද්ධතියේ නවමු භාවිත කරන්නා පිලිබද තොරතුරු දත්ත පද්ධතිය තුල යාවත්කාලීන වීම අසාර්ථක බැවින් කරුණාකර නැවත උත්සහ කරන්න");
                rem.setVisible(true);
            }
        }else{
            FormValidation fv = new FormValidation();
            fv.set_error_message("කරුණාකර අනිවාර්ය කරුණු සියල්ල නිසි ලෙස යතුරුලියනය කර ඇති දැයි පරීක්ෂා කරන්න");
            fv.setVisible(true);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.nameText.setText("");
        this.userNameText.setText("");
        this.passwordText.setText("");
        this.user_id = 0;
    }//GEN-LAST:event_cancelButtonActionPerformed

    DefaultListModel demoList = new DefaultListModel();
    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        // TODO add your handling code here:
        demoList.removeAllElements();
        
        String text = nameText.getText();
        UserController uc = new UserController();
        List<String> l = new ArrayList<String>();
        try{            
            l = uc.user_list(text);
            if(!l.isEmpty() || l != null){
                for(String t : l){
                    demoList.addElement(t);
                }
            }else{
                demoList.addElement("- අදාල ප්‍රතිපල දත්ත පද්ධතියේ නොමැතිය -");
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            demoList.addElement("- අදාල ප්‍රතිපල දත්ත පද්ධතියේ නොමැතිය -");
        }
        userList.setModel(demoList);
        jScrollPane1.setVisible(true);
        
    }//GEN-LAST:event_nameTextKeyReleased

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
        // TODO add your handling code here:
        JList l = (JList) evt.getSource();
        if(evt.getClickCount() >= 1){
            int index = l.locationToIndex(evt.getPoint());
            if(index >= 0){
                Object o = l.getModel().getElementAt(index);
                String name = o.toString();
                nameText.setText("");
                //nameText.setEditable(false);
                                
                DefaultListModel dlm = (DefaultListModel) userList.getModel();
                dlm.removeAllElements();
                
                int id = this.getIdFromString(name);
                if(id > 0){
                    this.user_id = id;                
                    UserController uc = new UserController();
                    List<String> list = new ArrayList<String>();
                    list = uc.getUserById(user_id);
                    this.nameText.setText(list.get(0));
                    this.userNameText.setText(list.get(1));
                    this.passwordText.setText(list.get(2));
                }
                
            }
        }
    }//GEN-LAST:event_userListMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        nameText.setText("");
        //nameText.setEditable(true);
        DefaultListModel dlm = (DefaultListModel) userList.getModel();
        dlm.removeAllElements();
        this.user_id = 0;
        this.nameText.setText("");
        this.userNameText.setText("");
        this.passwordText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private int getIdFromString(String strg){
        int rtn = -1;
        if(strg.charAt(0)=='-'){ return rtn; }
        try{
            String arr[] = strg.split("-");
            rtn = Integer.parseInt(arr[0]);
        }catch(Exception ex){
            System.out.println(ex);
        }
        return rtn;        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField passwordText;
    private javax.swing.JList<String> userList;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
